spring:
  application:
    name: petstoreorderservice
  cloud:
    azure:
      cosmos:
        uri: https://demo-cosmos-db.documents.azure.com:443/
        key: trial
        database: petOderDB
#    spring.cloud.azure.cosmos.endpoint=<YOUR_COSMOS_DB_URI>
#    spring.cloud.azure.cosmos.key=<YOUR_COSMOS_DB_PRIMARY_KEY>
#    spring.cloud.azure.cosmos.database=<YOUR_DATABASE_NAME>
server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8080}

petstore:
  service:
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    ssl:
      enabled: false
    diskspace:
      enabled: false

logging:
  level:
    root: INFO
    com.chtrembl: DEBUG
